### ISSUE TITLE
Fails to load and display request bodies from HAR

### ISSUE THREAD

**Issue by turf00** [httptoolkit/feedback#64] opened 2020-04-21 09:27 UTC
When capturing requests I can see the request bodies for PUT, POSTs as expected.

If I export these to a HAR, I can load the HAR into Chrome and also see the request bodies.

If I load the HAR into HttpToolkit, then the request body section is missing but I do still see the response bodies.

**Comment by pimterry** [comment] 2020-04-21 09:35
Yes, I can reproduce that too. That's clearly a bug, not sure what's happened there. I'll look into it now!

**Comment by pimterry** [comment] 2020-04-21 10:08
This is [now fixed](https://github.com/httptoolkit/httptoolkit-ui/commit/463d7fed766fbcabb2ceb523800538d460a05530). Although the HAR request body was imported correctly, the resulting imported request could be considered as incomplete (i.e. the status & headers have arrived, but the body hasn't yet) and in that case the request body section would be hidden. Looks like this came in due to some changes recently that expanded some of this request state tracking.

That's fixed and deployed, the new version should update in the background next time you start the app. Thanks for letting me know!

**Closed by pimterry** 2020-04-21 10:08 UTC

**Comment by turf00** [comment] 2020-04-21 12:56
Thanks for the fast turn around!  Working as expected now.
