### ISSUE TITLE
Application crash on Ubuntu with 'Unexpected token }' 

### ISSUE THREAD

**Issue by jdecool** [httptoolkit/feedback#18] opened 2019-01-12 13:22 UTC
Hi Tim,

Thanks for this tool. I just download the `.deb` file, but I can't test it on my computer because the application crash after display the main windows.

Log output :

```
$ httptoolkit
undefined:28
}}
 ^

SyntaxError: Unexpected token } in JSON at position 662
    at JSON.parse (<anonymous>)
    at /usr/lib/httptoolkit/resources/app/httptoolkit-server/node_modules/@james-proxy/james-browser-launcher/lib/config.js:35:34
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:408:3)
undefined:28
}}
 ^

SyntaxError: Unexpected token } in JSON at position 662
    at JSON.parse (<anonymous>)
    at /usr/lib/httptoolkit/resources/app/httptoolkit-server/node_modules/@james-proxy/james-browser-launcher/lib/config.js:35:34
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:408:3)
undefined:28
}}
 ^

SyntaxError: Unexpected token } in JSON at position 662
    at JSON.parse (<anonymous>)
    at /usr/lib/httptoolkit/resources/app/httptoolkit-server/node_modules/@james-proxy/james-browser-launcher/lib/config.js:35:34
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:408:3)
Failed to start server, exiting. Error: Server shutdown unexpectedly with code 1.
    at Promise.then (/usr/lib/httptoolkit/resources/app/src/index.ts:149:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

Some information about my Ubuntu version :

```
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.1 LTS"

$ uname -r
 4.15.0-43-generic
```

**Comment by jdecool** [comment] 2019-01-12 13:55
Thanks for your quick answer.

```
$ cat ~/.config/httptoolkit/browsers.json
{
  "browsers": [
    {
      "regex": {},
      "profile": true,
      "type": "firefox",
      "name": "firefox",
      "command": "firefox",
      "version": "64.0.2"
    },
    {
      "regex": {},
      "profile": "/home/jeremy/.config/httptoolkit/chrome-beta-72.0.3626.53_38ed98f181f8a",
      "type": "chrome",
      "name": "chrome-beta",
      "command": "google-chrome-beta",
      "version": "72.0.3626.53"
    },
    {
      "regex": {},
      "profile": "/home/jeremy/.config/httptoolkit/chrome-71.0.3578.98_cc19606e56564",
      "type": "chrome",
      "name": "chrome",
      "command": "google-chrome",
      "version": "71.0.3578.98"
    }
  ]
}}
  ]
}
```

It's append the first time I ran the app, just after install the `.deb` package.

After deleting the file, the problem disappeared.

**Comment by pimterry** [comment] 2019-01-12 14:06
Perfect, thanks! Yeah, that's super weird, it's just gained an extra `}]}` at the end. Still not sure why that'd happen, but it's a useful example to investigate further anyway. Glad it's sorted for you now, let me know if you have issues again, and I'll try to hunt down the cause and push a general fix for this soon.

**Comment by pimterry** [comment] 2019-01-17 11:07
This should now be totally fixed. New installs will never see this issue, and existing installs will update in the background on their next run, and then never see it either. Thanks again for reporting it!

**Closed by pimterry** 2019-01-17 11:07 UTC

**Comment by jdecool** [comment] 2019-01-18 07:53
👍 Great ! Thanks.
